using DTOMaker.SrcGen.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace DTOMaker.SrcGen.JsonSystemText
{

    [Generator]
    public sealed class JsonSTSourceGenerator : SourceGeneratorBase
    {
        protected override void OnBeginInitialize(IncrementalGeneratorInitializationContext context)
        {
        }
        protected override void OnEndInitialize(IncrementalGeneratorInitializationContext context, IncrementalValuesProvider<OutputEntity> entities)
        {
            // generate entities
            context.RegisterSourceOutput(entities, (spc, ent) =>
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine($"// FullName : {ent.FullName}");
                sb.AppendLine($"// Namespace: {ent.NameSpace}");
                sb.AppendLine($"// IntfName : {ent.IntfName}");
                sb.AppendLine($"// Base     : {ent.BaseFullName ?? "(null)"}");
                sb.AppendLine($"// Id       : {ent.EntityId}");
                sb.AppendLine($"// Height   : {ent.ClassHeight}");
                sb.AppendLine($"// Members  : {ent.Members.Count}");
                foreach (var member in ent.Members)
                {
                    sb.AppendLine($"// {member.Sequence,3}: {member.PropName}");
                }
                string implName = ent.IntfName.Substring(1);
                string hintName = $"{ent.NameSpace}.JsonSystemText.{implName}.g.cs";
                spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }
    }
}
