using DTOMaker.SrcGen.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace DTOMaker.SrcGen.JsonSystemText
{

    [Generator]
    public sealed class JsonSTSourceGenerator : SourceGeneratorBase
    {
        protected override void OnBeginInitialize(IncrementalGeneratorInitializationContext context)
        {
        }
        protected override void OnEndInitialize(IncrementalGeneratorInitializationContext context, IncrementalValuesProvider<ModelEntity> model)
        {
            // generate entities
            context.RegisterSourceOutput(model, (spc, ent) =>
            {
                string implName = ent.IntfName.Substring(1);
                // todo move to derived class
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine($"// Namespace: {ent.NameSpace}");
                sb.AppendLine($"// Name     : {implName}");
                sb.AppendLine($"// Id       : {ent.EntityId}");
                sb.AppendLine($"// Members  : {ent.Members.Count}");
                string hintName = $"{ent.NameSpace}.JsonSystemText.{implName}.g.cs";
                spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
            });

        }
    }
}
